# Generated by Django 5.2.15 on 2026-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image_url',
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/', verbose_name='Фото'),
        ),
    ]
